services:
  mqtt_sensehat:
    build: ghcr.io/rippleFCL/mqtt-sensehat:latest
    container_name: mqtt_sensehat
    restart: unless-stopped
    privileged: true
    volumes:
      - ./config.yml:/app/config.yml
